local redconvar = GetConVar("bleedout_outline_color_r")
local greenconvar = GetConVar("bleedout_outline_color_g")
local blueconvar = GetConVar("bleedout_outline_color_b")
hook.Add("AddToolMenuCategories", "BleedOutMenuAdd", function() 
	spawnmenu.AddToolCategory("Options", "BleedOutMenu", "#Revive System") // Создаем менюшку для настроек BleedOut'а
end)
if table.IsEmpty( file.Find("bleedout.txt", "DATA") )then
	bindingstab = {
		bleedout_suicide = KEY_G,
		bleedout_help = KEY_H
	}
	local filetxt = util.TableToJSON(bindingstab, true)
	file.Write("bleedout.txt", filetxt)
else
	local filetxt = file.Read("bleedout.txt", "DATA")
	bindingstab = util.JSONToTable(filetxt)
end
local itextures = file.Find("materials/bleedout/*.png", "MOD")
hook.Add("PopulateToolMenu", "BleedOutMenuPopulate", function() // Наполняем менюшку
	spawnmenu.AddToolMenuOption("Options", "BleedOutMenu", "BleedOutAdmin", "#Admin", "", "", function(panel)
		panel:ClearControls()
		panel:CheckBox("Enable Revive System", "bleedout_enable")
		panel:CheckBox("Should players take damage in BleedOut", "bleedout_shouldtakedmg")
		panel:CheckBox("Should players bleed in bleedout", "bleedout_enable_bleeding")
		panel:CheckBox("Should players shoot in bleedout", "bleedout_shouldshoot")
		panel:ControlHelp("Setting this ^ to false will fix the ArcCW crash")
		panel:CheckBox("Notarget in bleedout", "bleedout_notarget")
		panel:CheckBox("Enable movement in bleedout", "bleedout_moving_enable")
		panel:CheckBox("Enable reviving from npcs", "bleedout_npc_can_revive")
		panel:CheckBox("Enable sounds", "bleedout_sound_enable")
		panel:CheckBox("Enable DSP effects", "bleedout_heartbeat")
		panel:CheckBox("Enable draw body", "bleedout_view_draw_body")
		panel:CheckBox("Revive on kill", "bleedout_reviveonkill")
		panel:NumSlider("Kills before revive", "bleedout_killcount", 1, 15, false)
		panel:NumSlider("Time before death", "bleedout_death_time", 1, 45, false)
		panel:NumSlider("Time before revive", "bleedout_revive_time", 1, 15, false)
		panel:NumSlider("Max. bleedouts per life", "bleedout_num_bleedouts", 1, 10, false)
		panel:NumSlider("How much HP in % will be", "bleedout_hp", 1, 100, false)
		panel:NumSlider("Reducing damage amount in bleedout", "bleedout_reducedmg", 0, 100, false)
	end)
	spawnmenu.AddToolMenuOption("Options", "BleedOutMenu", "BleedOutClient", "#Client", "", "", function(panel)
		panel:ClearControls()
		panel:CheckBox("Draw oultines", "bleedout_draw_outlines")
		panel:CheckBox("Draw icons", "bleedout_draw_icons")
		panel:CheckBox("Draw blood", "bleedout_draw_blood")
		panel:CheckBox("Draw Black n' White?", "bleedout_blacknwhite")
		panel:CheckBox("Draw colorсorrection", "bleedout_draw_colorcorrection")
		panel:CheckBox("Draw death timer", "bleedout_draw_timer")
		panel:CheckBox("Draw revive timer", "bleedout_draw_revive_timer")
		panel:CheckBox("Enable view roll", "bleedout_view_roll")
		local combobox, labl = panel:ComboBox("Icon draw mode", "bleedout_icon_drawmode")
		combobox:AddChoice( "3D mode", 1 )
		combobox:AddChoice( "2D mode", 0 )
//		panel:CheckBox("Enable custom icons", "bleedout_icon_custom_enable")
		local combobox1, labl1 = panel:ComboBox("Bleedout icon", "bleedout_icon_custom")
		combobox1:AddChoice( "SKULL", "bleedout/REVIVESKULL.png" )
		combobox1:AddChoice( "CoD-Styled", "bleedout/REVIVEICON.png" )
		for k, v in pairs(itextures) do
			itexture = "bleedout/" .. tostring(v)
			combobox1:AddChoice( tostring(v), itexture ) // Тут находятся кастомные файлики
		end
		panel:Help("You need to place your .png icons to 'GAMEFOLDER/garrysmod/materials/bleedout' path. Then restart server/rejoin server.")
		local combobox2, labl2 = panel:ComboBox("HUD-Style", "bleedout_legacyui")
		combobox2:AddChoice( "Circle-Styled", 0 )
		combobox2:AddChoice( "Circle-Styled(Outlined)", 3 )
		combobox2:AddChoice( "Bar-Styled", 1 )
		combobox2:AddChoice( "Text-Styled", 2 )
//		panel:Help(" You can choose the HUD style if you want.")
		colormixer = vgui.Create("DColorMixer")
		colormixer:SetAlphaBar(false)
		colormixer:SetColor( Color( redconvar:GetInt(), greenconvar:GetInt(), blueconvar:GetInt() ) )
		colormixer:SetPalette(false)
		colormixer:SetConVarR("bleedout_outline_color_r")
		colormixer:SetConVarG("bleedout_outline_color_g")
		colormixer:SetConVarB("bleedout_outline_color_b")
		colormixer:SetLabel("Outline color")
		panel:AddItem(colormixer)
	//	panel:NumSlider("Outline color red", "bleedout_outline_color_r", 0, 255, false)
	//	panel:NumSlider("Outline color green", "bleedout_outline_color_g", 0, 255, false)
	//	panel:NumSlider("Outline color blue", "bleedout_outline_color_b", 0, 255, false)
		local dbinder1 = vgui.Create("DBinder")
		dbinder1:SetValue(bindingstab.bleedout_suicide)
		dbinder1:SetSize(32, 35)
		function dbinder1:OnChange(number)
			bindingstab.bleedout_suicide = number
			local filetxt = util.TableToJSON(bindingstab, true)
			file.Write("bleedout.txt", filetxt)
		end
		local dbinder2 = vgui.Create("DBinder")
		dbinder2:SetValue(bindingstab.bleedout_help)
		dbinder2:SetSize(32, 35)
		function dbinder2:OnChange(number)
			bindingstab.bleedout_help = number
			local filetxt = util.TableToJSON(bindingstab, true)
			file.Write("bleedout.txt", filetxt)
		end
		panel:ControlHelp("Suicide")
		panel:AddItem(dbinder1)
		panel:ControlHelp("Call for help")
		panel:AddItem(dbinder2)
	end)
end)