if CLIENT then
	concommand.Add("bleedout_suicide", function() net.Start("bleedout_suicide") net.SendToServer() end, nil, "Command1", FCVAR_NONE)
	concommand.Add("bleedout_help", function() net.Start("bleedout_help") net.SendToServer() end, nil, "Command2", FCVAR_NONE)
end
CreateConVar( "bleedout_shouldtakedmg", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Controls taking damage when player is in bleedout.", 0, 1 )
CreateConVar( "bleedout_enable", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Enables bleedout for players. 1 - on / 0 - off.", 0, 1 )
CreateConVar( "bleedout_enable_bleeding", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Enables/disables drawing blood.", 0, 1)
CreateConVar( "bleedout_death_time", 30, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Controls how much time needs for death.", 1, 300 )
CreateConVar( "bleedout_revive_time", 5, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Controls how much time needs for revive player.", 1, 100 )
CreateConVar( "bleedout_num_bleedouts", 3, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Controls the maximum bleedouts per life.", 0, 500 )
CreateConVar( "bleedout_notarget", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "If set - the player in bleedout will be in notarget mode (invisible for npc's).", 0, 1 )
CreateConVar( "bleedout_reducedmg", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Controls the amount of reducing damage in bleedout.", 0, 100 )
CreateConVar( "bleedout_moving_enable", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Enables/disables moving while in bleedout.", 0, 100 )
CreateConVar( "bleedout_npc_can_revive", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Enables/disables ability to be revived by npc.", 0, 1)
CreateConVar( "bleedout_view_draw_body", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Enables full body drawing.", 0, 1 )
CreateConVar( "bleedout_sound_enable", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Enables sound (help!, here's medkit).", 0, 1 )
CreateConVar( "bleedout_icon_drawmode", 1, FCVAR_ARCHIVE, "Controls icon drawing mode.", 0, 1 )
CreateConVar( "bleedout_draw_outlines", 0, FCVAR_ARCHIVE, "Conrols drawing player outlines.", 0, 1 )
CreateConVar( "bleedout_draw_icons", 1, FCVAR_ARCHIVE, "Conrols drawing player revive icons.", 0, 1 )
CreateConVar( "bleedout_draw_blood", 0, FCVAR_ARCHIVE, "Conrols drawing player's blood on screen.", 0, 1 )
CreateConVar( "bleedout_draw_colorcorrection", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "Conrols drawing colorcorrection.", 0, 1 )
CreateConVar( "bleedout_draw_timer", 1, FCVAR_ARCHIVE, "Conrols drawing timer.", 0, 1 )
CreateConVar( "bleedout_draw_revive_timer", 1, FCVAR_ARCHIVE, "Conrols drawing revive timer.", 0, 1 )
CreateConVar( "bleedout_outline_color_r", 255, FCVAR_ARCHIVE, "Controls outline color (Red).", 0, 255 )
CreateConVar( "bleedout_outline_color_g", 255, FCVAR_ARCHIVE, "Controls outline color (Green).", 0, 255 )
CreateConVar( "bleedout_outline_color_b", 255, FCVAR_ARCHIVE, "Controls outline color (Blue).", 0, 255 )
CreateConVar( "bleedout_shouldshoot", 1, FCVAR_ARCHIVE + FCVAR_REPLICATED, "If enabled - the players will have ability to shoot.", 0, 1)
CreateConVar( "bleedout_reviveonkill", 0, FCVAR_ARCHIVE + FCVAR_REPLICATED, "If enabled - the players'll be revived after kill.", 0, 1)
CreateConVar( "bleedout_killcount", 5, FCVAR_ARCHIVE + FCVAR_REPLICATED, "How much npc you need to kill before self-revive.", 1, 15)
CreateConVar( "bleedout_icon_custom", "bleedout/REVIVEICON.png", FCVAR_ARCHIVE, "You need to choose the custom icon location what is relative to materials folder. Example: bleedout/REVIVEICON.png - default icon.")
CreateConVar( "bleedout_icon_size", 50, FCVAR_ARCHIVE, "Controls the icon size.", 0, 500 )
CreateConVar( "bleedout_legacyui", 3, FCVAR_ARCHIVE, "If enabled - will change default UI into Legacy UI. (+fps)", 0, 3 )
CreateConVar( "bleedout_view_roll", 1, FCVAR_ARCHIVE, "Adds the 'roll' in view when in bleedout", 0, 1 )
CreateConVar( "bleedout_hp", 10,FCVAR_REPLICATED, "How much hp will be in percents", 0, 100 )
CreateConVar( "bleedout_blacknwhite", 0, FCVAR_ARCHIVE, "Conrols drawing black n' white effect.", 0, 1 )
CreateConVar( "bleedout_heartbeat", 1, FCVAR_ARCHIVE, "Conrols heartbeat effect while in bleedout.", 0, 1 )
